# Use custom format
format = '$directory${custom.worktree_repo}$all'

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false 


[character]
success_symbol = '[âžœ](bold green)'
error_symbol = '[âžœ](bold red)'

[directory]
format = '[\[$path\]]($style)(${read_only}) '
truncation_symbol = 'â€¦/'
truncation_length = 8

[git_branch]
symbol = "î‚ "
format = '[${symbol}${branch}](bold green)'

[nodejs]
symbol = "â¬¢"
format = "($symbol${version}) "

[python]
pyenv_version_name = true
symbol = "ðŸ"
#format = "${pyenv_prefix}${version}${pyenv_version_name}${virtualenv}"
format = '[${symbol}(${virtualenv} )${version} ](purple)'

[rust]
symbol = "ðŸ¦€"
format = "($symbol${version})"

[package]
symbol='ðŸ“¦'
format = '[$symbol$version]($style) '

[palettes.foo]
mustard = '#af8700'

[git_status]
format = '([$all_status$ahead_behind]($style)) '
staged = '[++\($count\)](green)'

[custom.worktree_repo]
command = "dirname $(git rev-parse --git-common-dir 2>/dev/null) | xargs basename"
when = "git rev-parse --git-dir 2>/dev/null | grep -q worktrees"
format = '[($output)]($style) '
style = 'bold #bd93f9'
